# Use AWS Lambda Python runtime as base - Python 3.11 is stable
FROM public.ecr.aws/lambda/python:3.11

# Copy requirements and install Python packages
COPY requirements-lambda.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r requirements-lambda.txt

# Copy cortex package
COPY cortex/ ${LAMBDA_TASK_ROOT}/cortex/

# Copy lambda handler
COPY lambda_handler.py ${LAMBDA_TASK_ROOT}/

# Set the handler
CMD ["lambda_handler.lambda_handler"]